env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
parserOptions:  
      ecmaVersion: 2020
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: 
    no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }] # разрешает подчёркивание в именах только для двух констант
