env:
  browser: true
  es2021: true
extends:
  - eslint:all
  - plugin:react/all
parserOptions:  
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: 
    no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }] # разрешает подчёркивание в именах только для двух констант
